### ISSUE TITLE
Build ld64 using Xcode 15.2

### ISSUE THREAD

**Issue by Chenyibo** [keith/ld64#2]
I want to compile ld64 locally using Xcode 15.2, and the version of ld64 I'm using is ld64-951.9. However, attempting to compile ld64 directly with Xcode results in many errors. Moreover, compiling ld64 requires dependencies such as dyld, llvm, and tapi, each with different versions. I'm unsure about which versions of these dependencies are needed to compile ld64-951.9. Could you provide a detailed compilation process, including downloading the necessary dependencies? @keith

**Comment by keith** [comment]
You should be able to build the `buildable-15.3` branch with Xcode 15.2. That has the version you want and the 15.3 in the branch name is just about what Xcode version that ld release corresponds to, not what is required to build it

**Comment by Chenyibo** [comment]
@keith I know how to build ld64 with Xcode 15.2, I have built ld64 successfully in local, thank you!

**Comment by keith** [comment]
Great!
